version: 2
registries:
  maven-repository-build-tis-nhs-uk-maven-repository:
    type: maven-repository
    url: https://build.tis.nhs.uk/maven/repository
    username: gradle
    password: "${{secrets.MAVEN_REPOSITORY_BUILD_TIS_NHS_UK_MAVEN_REPOSITORY_PASSWORD}}"

updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: io.sentry:sentry-spring
    versions:
    - 4.0.0
    - 4.1.0
    - 4.2.0
    - 4.3.0
  - dependency-name: org.springframework.boot
    versions:
    - 2.4.2
  - dependency-name: org.mapstruct:mapstruct-processor
    versions:
    - 1.4.1.Final
  - dependency-name: org.mapstruct:mapstruct
    versions:
    - 1.4.1.Final
  registries:
  - maven-repository-build-tis-nhs-uk-maven-repository
