server:
  port: 8208
  servlet:
    context-path: /sync

service:
  reference:
    host: ${REFERENCE_HOST:localhost}
    port: ${REFERENCE_PORT:8205}
    url: http://${service.reference.host}:${service.reference.port}/reference
  trainee:
    host: ${TRAINEE_DETAILS_HOST:localhost}
    port: ${TRAINEE_DETAILS_PORT:8203}
    url: http://${service.trainee.host}:${service.trainee.port}/trainee

spring:
  data:
    mongodb:
      uri: mongodb://${DB_USER:admin}:${DB_PASSWORD:pwd}@${DB_HOST:localhost}:${DB_PORT:27017}/${DB_NAME:sync}?authSource=${AUTH_SOURCE:admin}

mongock:
  migration-scan-package: uk.nhs.hee.tis.trainee.sync.migration

application:
  aws:
    sqs:
      placement: ${PLACEMENT_QUEUE_URL:}
      placement-specialty: ${PLACEMENT_SPECIALTY_QUEUE_URL:}
      profile-created: ${PROFILE_CREATED_QUEUE_URL:}
      post: ${POST_QUEUE_URL:}
      record: ${RECORD_QUEUE_URL:}
      request: ${REQUEST_QUEUE_URL:}

logging:
  level:
    root: ${LOGGING_ROOT:INFO}
    uk:
      nhs:
        hee:
          tis:
            trainee:
              sync:
                event: ${LOGGING_EVENT:DEBUG}
                service: ${LOGGING_SERVICE:DEBUG}

sentry:
  dsn: ${SENTRY_DSN:}
  environment: ${SENTRY_ENVIRONMENT:local}
